name: d4_hierarchy
version: 0.1.0
description: 2D layout algorithms for visualizing hierarchical data.
repository: https://github.com/luizbarboza/d4_hierarchy

environment:
  sdk: '>=3.3.0 <4.0.0'

dev_dependencies:
  d4_array: ^1.0.0
  d4_dsv: ^1.0.0
  lints: ^2.1.1
  test: ^1.22.0